/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_listedesETS_J (void);
GtkWidget* create_ajoutETS_J (void);
GtkWidget* create_modifierETS_J (void);
GtkWidget* create_triregion_J (void);
GtkWidget* create_tricap_J (void);
GtkWidget* create_choixtri_J (void);
GtkWidget* create_choixacteur (void);
GtkWidget* create_acceuil_admin (void);
GtkWidget* create_login_admin_b_j (void);
GtkWidget* create_liste_util_b (void);
GtkWidget* create_form_ajout_b (void);
GtkWidget* create_statistiques_baha (void);
GtkWidget* create_affichage_role_b (void);
GtkWidget* create_pourcentage_par_sexe_b (void);
GtkWidget* create_supprimer_b (void);
GtkWidget* create_supprimer_j (void);
GtkWidget* create_espace_donneur_ak (void);
GtkWidget* create_gestion_RV_ak (void);
GtkWidget* create_supprimer_ak (void);
GtkWidget* create_modification_RDV_ak (void);
GtkWidget* create_ajout_RDV_ak (void);
GtkWidget* create_rendez_vous_dispo_ak (void);
GtkWidget* create_historique_rdv (void);
GtkWidget* create_form_modif_b (void);
GtkWidget* create_listeETS (void);
