/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *listedesETS_J;
  GtkWidget *ajoutETS_J;
  GtkWidget *modifierETS_J;
  GtkWidget *triregion_J;
  GtkWidget *tricap_J;
  GtkWidget *choixtri_J;
  GtkWidget *choixacteur;
  GtkWidget *acceuil_admin;
  GtkWidget *login_admin_b_j;
  GtkWidget *liste_util_b;
  GtkWidget *form_ajout_b;
  GtkWidget *statistiques_baha;
  GtkWidget *affichage_role_b;
  GtkWidget *pourcentage_par_sexe_b;
  GtkWidget *supprimer_b;
  GtkWidget *supprimer_j;
  GtkWidget *espace_donneur_ak;
  GtkWidget *gestion_RV_ak;
  GtkWidget *supprimer_ak;
  GtkWidget *modification_RDV_ak;
  GtkWidget *ajout_RDV_ak;
  GtkWidget *rendez_vous_dispo_ak;
  GtkWidget *historique_rdv;
  GtkWidget *form_modif_b;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */

  choixacteur = create_choixacteur ();
  gtk_widget_show (choixacteur);
  

  gtk_main ();
  return 0;
}

